### ISSUE TITLE
The `combine_lookups` function 

### ISSUE THREAD

**Issue by Antonio95** [a16z/Lasso#139]
This issue is rather a question. The `JoltInstruction` trait contains a function called `combine_lookups` ([here](https://github.com/a16z/Lasso/blob/moodlezoup/jolt/jolt-core/src/jolt/instruction/mod.rs#L25)). I understand this is meant to represent the polynomial `g` from the Lasso and Jolt preprints (e.g. Jolt preprint, definition 2.6) and it receives the lookups `T_i(r_j)` of suitable chunks in suitable subtables.

- Am I correct in thinking that, even though this function can contain any Rust code, it should strictly perform a polynomial evaluation on its input? Although this is perhaps not meant to be an extensible library at the moment, it would seem natural to enforce this on the code level.
- In particular, `combine_lookups` should not e.g. use the instruction's input data, such as `self.0` (in the implementors that have such a field) directly, correct?
- I understand the `degree` function of in the `JoltInstruction` trait should return the degree of the polynomial `g` computed by `combine_lookups`. But is this degree variable-wise, or monomial-wise? In other words, should `g(x_1, x_2) = x_1 * x_2` return 1 or 2? I'm guessing the latter, since the Jolt paper estipulates `g` should be a multilinear polynomial and hence have variable-wise degree <= 1.

Thank you for sharing this excellent library!

**Comment by moodlezoup** [comment]
Yes, correct on all fronts :)
- Correct, `combine_lookups` should always be a polynomial evaluation on the input, as it is typically part of a sumcheck summand
- Yes, also correct. The reason you see `self` as an argument to `combine_lookups` is a somewhat annoying artifact of using `enum_dispatch` on the `JoltInstruction` trait
- Yes, it's monomial-wise

**Comment by Antonio95** [comment]
I see, this is very useful! Thank you very much again.

The issue can be safely closed
