### ISSUE TITLE
Use Quarks Grand Product Argument

### ISSUE THREAD

**Issue by sragss** [a16z/Lasso#17]

**Comment by PatStiles** [comment]
Is this a reference to Section 5 of https://eprint.iacr.org/2020/1275.pdf?

**Comment by PatStiles** [comment]
This refers to this optimization correct? 
![image](https://github.com/a16z/Lasso/assets/33334338/eb26e6ea-02d2-4c6d-b192-d27ddbe7d57e)

**Comment by 0xfuturistic** [comment]
could you elaborate more @sragss?
