### ISSUE TITLE
Parallelize Sumcheck::prove_arbitrary summation

### ISSUE THREAD

**Issue by sragss** [a16z/Lasso#31]
Feature gate with "multicore"

**Comment by 0xfuturistic** [comment]
done! could you please review #54? @moodlezoup @sragss

**Comment by sragss** [comment]
#54 is great but does not quite close the issue.

The main cost in `prove_arbitrary` is that big accumulation of field work. This can also be heavily parallelized with a proper accumulation strategy and is the lowest hanging fruit for large decreases in prover costs thanks to parallelism.
