### ISSUE TITLE
Parallelize `to_grand_products`

### ISSUE THREAD

**Issue by moodlezoup** [a16z/Lasso#33]
Currently processes each dimension (1..C) in serial, but this can be parallelized.

**Comment by shryasss** [comment]
Hi @moodlezoup, I am interested in working on this issue, can you please explain this in detail for me to pick it up and submit a PR.

**Comment by 0xfuturistic** [comment]
Just posted a complete solution in #51. Could you review it please? @sragss @moodlezoup
