### ISSUE TITLE
Build error due to incompatible version of packages related to clap

### ISSUE THREAD

**Issue by 0xfuturistic** [a16z/Lasso#52]
When building, the following error occurs: 
`package `clap_derive v4.4.2` cannot be built because it requires rustc 1.70.0 or newer, while the currently active rustc version is 1.66.0-nightly`

A solution could be to update the version of the (nightly) rust-toolchain used.

**Comment by 0xfuturistic** [comment]
Fixed in #53. Lmk your thoughts @moodlezoup @sragss!

**Comment by moodlezoup** [comment]
Thank you for the fix!
