### ISSUE TITLE
[Question] How could we use Lasso to solve real problems?

### ISSUE THREAD

**Issue by ClaudeZsb** [a16z/Lasso#59]
Hi, developers of Lasso, I recently got to know and learn about this impressive project. 

After I have an idea about how to write a subtable, I'm getting excited and want to solve some more complicated problems with the help of those subtables from `src/subtables`.  Like calculating `((a AND b) XOR b) OR a` with help of subtable `AND`, `OR` and `XOR`.

But I really don't have a strong background of `lookup argument` and `surge`. This makes me not even know where to start. So if Lasso is able to solve any real problems, is there anybody could help me with it? A doc or tutorial would help a lot. Thanks in advance.

**Comment by moodlezoup** [comment]
Hi, you may find these lectures by Justin Thaler helpful for context:
[Part 1](https://youtu.be/aEiHLORcDq4)
[Part 2](https://youtu.be/dmVweFbJsxw)
